### ISSUE TITLE
[BUG]: Roller mission looping sowing mission on the same field

### ISSUE THREAD

**Issue by westor7** [tn4799/RollerMission#7]
Hello,

I noticed there is a looping bug due ROLLING and SOWING and i will try to explain as much i can, sorry for my english.

So i first took a roller mission then i finished that field and i click to collect the contract, after 1-2 game hours that field is appearing on contracts to sow again, thats not normal because i've already completed a rolling mission before, i took a video to show you what is going on, i am using BetterContracts mod and i have already report this on their side too https://github.com/Mmtrx/FS22_BetterContracts/issues/146 because i am not sure if its their side bug or this mod one.

**NOTE**: This bug is not happening if i disable the BetterContracts mod, so my thought is that these two are not compatible for some reasons.

Log.txt: [log.txt](https://github.com/tn4799/RollerMission/files/12698656/log.txt)

Video: https://ufile.io/j1xq735r

- Thanks!

**Comment by tn4799** [comment]
Thanks for reporting. 
I've found the bug and fixed it. Release coming soon

**Comment by westor7** [comment]
@tn4799 any new release yet?

- Thanks!

**Comment by tn4799** [comment]
Damn, stupid modhub UI. 
I've thought i've released it already because in the modhub modder UI the last updated-date was way newer. My fault.

I will submit immediatly. And I will create a Release here on github so you can download the update right away

**Comment by westor7** [comment]
@tn4799 

Appreciated mate, thanks for the mod and the fix. keep giving us your best! we love u.
